codecov:
  require_ci_to_pass: no
  max_report_age: off

comment: false

ignore:
  - "extras"

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 80
        informational: true
    patch: off
    changes: off
