codecov:
  max_report_age: off

comment: false

ignore:
  - "xdevbot/routes.py"
  - "xdevbot/polling.py"
  - "xdevbot/queries.py"

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        threshold: 0.2
        if_not_found: success
        if_ci_failed: success
    patch:
      default:
        enabled: no
        if_not_found: success
        if_ci_failed: success
    changes:
      default:
        enabled: no
        if_not_found: success
        if_ci_failed: success
