version: 2

workflows:
  version: 2
  default:
    jobs:
      - tests:
          filters:
            branches:
              ignore:
                - gh-pages

jobs:
  tests:
    docker:
      - image: continuumio/miniconda3:latest
    environment:
      ENV_FILE: ".circleci/environment.yml"
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum ".circleci/environment.yml" }}
      - run:
          name: Install dependencies in base environment
          command: conda env update -n base -f ${ENV_FILE}
      - run:
          name: List packages in the current environment (base)
          command: conda list
      - run:
          name: Running tests
          command: python -m pytest --junitxml=test-reports/junit.xml --cov=./ --verbose
      - run:
          name: Uploading code coverage report
          command: codecov
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
      - save_cache:
          key: deps-{{ checksum ".circleci/environment.yml" }}
          paths:
            - "/opt/conda/pkgs"
