name: xdevbot
channels:
  - conda-forge
dependencies:
  - python=3.8
  - aiohttp
  - aiohttp-jinja2
  - click
  - bs4
  - pytest
  - pytest-aiohttp
  - pytest-cov
  - pip
  - pip:
    - -e git+https://github.com/codecov/codecov-python#egg=codecov
    - motor
    - dnspython
    - mockupdb
