name: xdevbot
channels:
  - conda-forge
dependencies:
  - python=3.8
  - fastapi
  - uvicorn
  - jinja2
  - bs4
  - pytest
  - pytest-asyncio
  - pytest-cov
  - codecov
  - pip
  - pip:
    - async-asgi-testclient
